---

- include: install.yml
  tags: install

- include: sysconf.yml
  tags: sysconf

- include: config.yml
  tags: config

- include: cluster.yml
  tags: cluster

- include: settings.yml
  tags: settings
