---

# Install rabbitmq from its own repository
# http://www.rabbitmq.com/install-debian.html

- name: Import repository key
  apt_key:
    url: https://www.rabbitmq.com/rabbitmq-release-signing-key.asc
    state: present
  tags: install

- name: Add RabbitMQ apt repository
  apt_repository:
    repo: "deb http://www.rabbitmq.com/debian/ testing main"
    filename: rabbitmq
    update_cache: yes
    state: present
  tags: install

- name: Install RabbitMQ server package
  apt:
    update_cache: yes
    force: yes
    pkg: rabbitmq-server
    state: present
  tags: install

# Configure system
- name: Ensure user and group are created
  group:
    name: "{{ rabbitmq_cluster_group }}"
    state: present
  tags:
    - install
    - user

- name: Ensure user and group are created
  user:
    name: "{{ rabbitmq_cluster_user }}"
    group: "{{ rabbitmq_cluster_group }}"
    state: present
    createhome: no
  tags:
    - install
    - user

- name: Ensure directories is configured
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ rabbitmq_cluster_user }}"
    group: "{{ rabbitmq_cluster_group }}"
    mode: 0755
  with_items:
    - "{{ rabbitmq_cluster_mnesia_base }}"
    - "{{ rabbitmq_cluster_log_base }}"
  tags: install

- name: Render logrotate config
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/rabbitmq-server
    owner: root
    group: root
    mode: 0644
  tags: config

# Configure RabbitMQ service

- name: Render RabbitMQ env file
  template:
    src: env.j2
    dest: /etc/rabbitmq/rabbitmq-env.conf
    owner: "{{ rabbitmq_cluster_user }}"
    group: "{{ rabbitmq_cluster_group }}"
    mode: 0644
  tags: config

- name: Render service unit file
  template:
    src: service.j2
    dest: /etc/systemd/system/rabbitmq-server.service
    owner: root
    group: root
    mode: 0644
  notify: service reload
  tags: config

# Configure RabbitMQ

- name: Render RabbitMQ config
  template:
    src: config.j2
    dest: /etc/rabbitmq/rabbitmq.config
    owner: "{{ rabbitmq_cluster_user }}"
    group: "{{ rabbitmq_cluster_group }}"
    mode: 0644
  tags: config

- name: Ensure RabbitMQ service
  systemd:
    name: rabbitmq-server
    enabled: yes
    state: started

- name: Enable RabbitMQ plugins
  rabbitmq_plugin:
    names: "{{ item }}"
    state: enabled
  with_items: "{{ rabbitmq_cluster_plugins }}"
  notify: service restart
  tags:
    - config
    - admin

- name: Remove disabled RabbitMQ users
  rabbitmq_user:
    user: "{{ item }}"
    state: absent
  with_items: "{{ rabbitmq_cluster_disabled_users }}"

- name: Ensure RabbitMQ users
  rabbitmq_user:
    user: "{{ item.user }}"
    password: "{{ item.password }}"
    configure_priv: "{{ item.configure_priv | default('.*') }}"
    read_priv: "{{ item.read_priv | default('.*') }}"
    write_priv: "{{ item.write_priv | default('.*') }}"
    vhost: "{{ item.vhost | default('/') }}"
    permissions: "{{ item.permissions | default(omit) }}"
  with_items: "{{ rabbitmq_cluster_users }}"
  tags:
    - config
    - admin
  #  no_log: true
