---

- name: service reload
  systemd: daemon_reload=yes

- name: service restart
  with_items: "{{ play_hosts }}"
  run_once: yes
  delegate_to: "{{ item }}"  # https://github.com/ansible/ansible/issues/12170
  systemd:
    name: rabbitmq-server
    state: restarted

- name: service stop
  systemd:
    name: rabbitmq-server
    state: stopped
